# Default configuration settings for Evo-Ros
# GAS 9-13-2017


# GA Server Script
ga_server:
   GA_IP_ADDR: '' # If left blank, will default to IP of the machine that the script is runnng on
   GA_SEND_PORT: 5000
   GA_RECV_PORT: 5010
   LOG_FILE_NAME: log.txt
   MAX_WAIT_TIME: 420000 # Max wait time on evaluation collection socket before we resend genomes in miliseconds
   POP_SIZE: 3 # How large the population size is for each generation
   GEN_COUNT: 3 # How many generations is this experiment going to run for
   MUTATION_PROB: 0.2 #Probability that an individual will have a random gene mutated
   CROSS_OVER_PROB: 0.35 #Probability that two individuals will cross over and producing mixed offspring
   TOURNAMENT_SIZE: 3 # Number of individuals that enter each selection tournament to create the next generation
   NUM_EVAL_WORKS: 1 # Number of workers (ROS instances) being used to run evaluations of indiviuals


# Software Manager Script
software_manager:
   GA_SEND_PORT: 5000
   GA_RECV_PORT: 5010
   GA_IP_ADDR: '35.12.212.131'
   VEHICLE: 'rover' # The vehicle that is being used. Default is the erle-rover
   SCRIPTS:
      rover:
         MAVPROXY_CMD_STR: |
            source ~/simulation/ros_catkin_ws/devel/setup.bash;
            cd ~/simulation/ardupilot/APMrover2;
            echo "param load ~/simulation/ardupilot/Tools/Frame_params/3DR_Rover.param";
            echo
            echo " (For manual control) - param set SYSID_MYGCS 255";
            echo
            echo " (For script control) - param set SYSID_MYGCS 1";
            ../Tools/autotest/sim_vehicle.sh -j 4 -f Gazebo
         ARDUPILOT_EXE: 'APMrover2.elf'
         LAUNCH_FILE: 'mission.launch'
         LAUNCH_FILE_PACKAGE: 'rover_ga'
         SIM_MANAGER_SCRIPT: 'rover_sim_manager.py'
         SIM_MANAGER_PACKAGE: 'evo_ros'
         CONTROLLER_SCRIPT: 'ga_dronekit_controller.py'
         CONTROLLER_SCRIPT_PACKAGE: 'rover_ga'
         
         
      copter:
         MAVPROXY_CMD_STR: |
             source ~/simulation/ros_catkin_ws/devel/setup.bash;
             cd ~/simulation/ardupilot/ArduCopter;
             echo "param load ~/simulation/ardupilot/Tools/Frame_params/Erle-Copter.param";
             ../Tools/autotest/sim_vehicle.sh -j 4 -f Gazebo
         ARDUPILOT_EXE: 'ArduCopter.elf'
         LAUNCH_FILE: 'erlecopter_spawn.launch'
         LAUNCH_FILE_PACKAGE: 'copter_ga'
         SIM_MANAGER_SCRIPT: ''
         SIM_MANAGER_PACKAGE: ''
         CONTROLLER_SCRIPT: 'copter_controller_ga.py'
         CONTROLLER_SCRIPT_PACKAGE: 'copter_ga'
   

# Transporter between GA server and Software Manager
tranporter: # Note: Software Manager is scripted to overwrite these values at run-time
   GA_SEND_PORT: 5000
   GA_RECV_PORT: 5010
   GA_IP_ADDR: '127.0.0.1'
   
rover_sim_manager:
   MAX_SIM_TIME: 240 # simulation seconds a simulation is allowed to run before ending 
